### ISSUE TITLE
about maple model

### ISSUE THREAD

**Issue by nicheng0019** [Mark-Sky/KCL#1]
![image](https://github.com/Mark-Sky/KCL/assets/8815106/003ed9bd-477f-45bc-9708-e34f3ee978c1)

how can I get the maple cache data? thank you

**Comment by Mark-Sky** [comment]
you can train a MaPLe model on each dataset with 1 to 16 shots, and save the image features and text features of maple, it's not difficult.

**Comment by nicheng0019** [comment]
OK
